version: '3.8'

services:
  api:
    build: .
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - PORT=3002
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - SUPABASE_PROJECT_ID=${SUPABASE_PROJECT_ID}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - COZE_API_KEY=${COZE_API_KEY}
      - COZE_BOT_ID=${COZE_BOT_ID}
      - COZE_API_ENDPOINT=${COZE_API_ENDPOINT}
      - COZE_GLOBAL_API_KEY=${COZE_GLOBAL_API_KEY}
      - COZE_GLOBAL_API_ENDPOINT=${COZE_GLOBAL_API_ENDPOINT}
      - COZE_GLOBAL_BOT_ID=${COZE_GLOBAL_BOT_ID}
      - DIFY_API_KEY=${DIFY_API_KEY}
      - DIFY_API_ENDPOINT=${DIFY_API_ENDPOINT}
      - OLLAMA_API_ENDPOINT=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL}
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_data:
